---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below. 
Title <- "Overt attentional capture by reward-related stimuli overcomes top-down suppression"
```

# vmacfeaturesearch

This repository contains the data and analysis code for our project investigating whether overt attention to reward-related distractors can be suppressed under feature search conditions.

This repository contains data files that have been derived from the raw eye-tracker data. The raw eye-gaze files are very large and so are not stored here. They can be found at: <https://osf.io/yrdzv/>.

Our pre-print is online here:

> Pearson, D., Watson, P., Cheng, P., Most, S. (2019). _`r Title`_. Name of journal/book, Accessed `r format(Sys.Date(), "%d %b %Y")`. Online at <https://doi.org/xxx/xxx>


### How to cite

Please cite this compendium as:

> Pearson, D., Watson, P., Cheng, P., & Le Pelley, M. (`r format(Sys.Date(), "%Y")`. Investigating attentional suppression of reward-related distractors. Retrieved from <https://osf.io/yrdzv>

### How to download or install

You can download the compendium as a zip from from this URL: <https://github.com/danielpearson90/vmacfeaturesearch/archive/master.zip>


### Licenses

**Text and figures :**  [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/), Copyright (c) 2019 Daniel Pearson.

**Code :** See the [DESCRIPTION](DESCRIPTION) file

**Data :** [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/), Copyright (c) 2019 Daniel Pearson.


